/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciostream;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;

/**
 *
 * @author tatip
 */
public class Personas extends javax.swing.JFrame {

    /**
     * Creates new form Personash
     */
    public Personas() {
        initComponents();
        mostrar();
        ordenar();
        tiempo();
    }

    List<Persona> personas = new ArrayList<>();

    public void tiempo() {

        long startTime = System.currentTimeMillis();
        txt_Ejecu.setText(String.valueOf(startTime));
    }

    public void lista() {
        try {

            List<String> lineas = Files.readAllLines(Paths.get("C:\\Users\\Carlo\\OneDrive\\Documentos\\TERCERO A\\Preogramacion Visual\\archivo.txt"));
            lineas.stream().map(linea -> linea.split(" ")).filter(datos -> datos.length >= 3).forEach(datos -> {
                String nombre = datos[0];
                String apellido1 = datos[1];
                String apellido2 = datos[2];

                Persona persona = new Persona();
                persona.setNombre(nombre);
                persona.setApellido1(apellido1);
                persona.setApellido2(apellido2);

                personas.add(persona);
            });

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void ordenar() {

        List<Persona> personasOrdenadas = personas.stream()
                .sorted(Comparator.comparing(Persona::getApellido1))
                .collect(Collectors.toList());

        String listaPersonas = personasOrdenadas.stream()
                .map(persona -> persona.getApellido1() + " " + persona.getApellido2() + " " + persona.getNombre())
                .collect(Collectors.joining("\n"));

        jTextArea1.setText(listaPersonas);

    }

    public void mostrar() {

        lista();

        String listaPersonas = personas.stream().map(persona -> persona.getNombre() + " " + persona.getApellido1() + " " + persona.getApellido2()).collect(Collectors.joining("\n"));

        txtListaPersonas.setText(listaPersonas);
    }

    public void buscar() {

        lista();

        String nombreBuscado = txtBuscaNombre.getText();
        String apellido1Buscado = txtApellidoP.getText();
        String apellido2Buscado = txtApellidoM.getText();

        Optional<Persona> personaEncontrada = personas.stream().filter(persona -> persona.getNombre().equals(nombreBuscado) && persona.getApellido1().equals(apellido1Buscado)
                && persona.getApellido2().equals(apellido2Buscado)).findFirst();

        personaEncontrada.ifPresentOrElse(persona -> txtResultadoBusqueda.setText("Persona encontrada: " + persona.getNombre() + " " + persona.getApellido1() + " "
                + persona.getApellido2()), () -> txtResultadoBusqueda.setText("No se encontró ninguna persona con los datos buscados."));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListaPersonas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarPersona = new javax.swing.JButton();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtBuscaNombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultadoBusqueda = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txt_Ejecu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtListaPersonas.setEditable(false);
        txtListaPersonas.setColumns(20);
        txtListaPersonas.setRows(5);
        jScrollPane1.setViewportView(txtListaPersonas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 240, 290));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar una Persona");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnBuscarPersona.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnBuscarPersona.setText("Buscar Persona");
        btnBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 290, -1));

        txtApellidoP.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        txtApellidoP.setForeground(new java.awt.Color(153, 153, 153));
        txtApellidoP.setText("Ingrese el apellido paterno");
        txtApellidoP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoPMouseClicked(evt);
            }
        });
        txtApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 290, 40));

        txtApellidoM.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        txtApellidoM.setForeground(new java.awt.Color(153, 153, 153));
        txtApellidoM.setText("Ingrese el apellido materno");
        txtApellidoM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoMMouseClicked(evt);
            }
        });
        txtApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 290, 40));

        txtBuscaNombre.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        txtBuscaNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscaNombre.setText("Ingrese el nombre");
        txtBuscaNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscaNombreMouseClicked(evt);
            }
        });
        txtBuscaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, 40));

        txtResultadoBusqueda.setColumns(20);
        txtResultadoBusqueda.setRows(5);
        jScrollPane2.setViewportView(txtResultadoBusqueda);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 290, 58));

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 70, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Resultado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 230, 290));

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lista de Personas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        txt_Ejecu.setEditable(false);
        jPanel1.add(txt_Ejecu, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonaActionPerformed
      
        buscar();
        long startTime = System.currentTimeMillis();
        txt_Ejecu.setText(String.valueOf(startTime));

    }//GEN-LAST:event_btnBuscarPersonaActionPerformed

    private void txtApellidoPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoPMouseClicked
        txtApellidoP.setText("");
    }//GEN-LAST:event_txtApellidoPMouseClicked

    private void txtApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPActionPerformed

    private void txtApellidoMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMMouseClicked
        txtApellidoM.setText("");
    }//GEN-LAST:event_txtApellidoMMouseClicked

    private void txtApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMActionPerformed
        txtApellidoM.setText("");
    }//GEN-LAST:event_txtApellidoMActionPerformed

    private void txtBuscaNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscaNombreMouseClicked
        txtBuscaNombre.setText("");
    }//GEN-LAST:event_txtBuscaNombreMouseClicked

    private void txtBuscaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtBuscaNombre;
    private javax.swing.JTextArea txtListaPersonas;
    private javax.swing.JTextArea txtResultadoBusqueda;
    private javax.swing.JTextField txt_Ejecu;
    // End of variables declaration//GEN-END:variables
}
